name: Python Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3  # Updated to v3 for newer features

      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to v4
        with:
          python-version: '3.10'  # Use quotes for string representation
          cache: 'pip'  # Optional: enables caching of pip dependencies

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pytest

      - name: Run black --check
        run: black --check app tests

      - name: Run tests
        run: pytest